name: Linux x64 Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup disk
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    

    - name: Setup Swap Space
      run: |
        echo Before:
        free -h
        df -h
        echo
        echo
        sudo swapoff /mnt/swapfile
        sudo rm /mnt/swapfile
        sudo fallocate -l 7G /home/runner/swapfile2
        sudo chmod 600 /home/runner/swapfile2
        sudo mkswap /home/runner/swapfile2
        sudo swapon /home/runner/swapfile2
        echo
        echo
        echo After:
        free -h
        df -h

    - name: Create environment
      run: |
        sudo apt install xvfb
        git clone https://github.com/floorp-projects/l10n-central.git
        ./mach bootstrap
        echo 'ac_add_options --with-app-name=floorp' >> mozconfig
        echo 'ac_add_options --with-app-basename=Floorp' >> mozconfig
        echo 'ac_add_options --with-branding=browser/branding/official' >> mozconfig
        echo 'ac_add_options --disable-crashreporter' >> mozconfig
        echo 'ac_add_options --enable-proxy-bypass-protection' >> mozconfig
        echo 'ac_add_options --disable-verify-mar' >> mozconfig
        echo 'ac_add_options --enable-update-channel=release' >> mozconfig
        echo 'ac_add_options --with-mozilla-api-keyfile=/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/floorp/apis/api-mozilla-key' >> mozconfig
        echo 'ac_add_options --with-google-location-service-api-keyfile=/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/floorp/apis/api-google-location-service-key' >> mozconfig
        echo 'ac_add_options --with-google-safebrowsing-api-keyfile=/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/floorp/apis/api-google-safe-browsing-key' >> mozconfig
        echo 'ac_add_options --enable-bootstrap' >> mozconfig
        echo 'ac_add_options --with-l10n-base=/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/l10n-central/l10n-central' >> mozconfig
        echo 'ac_add_options --enable-optimize="-O3"' >> mozconfig
        echo 'ac_add_options --enable-lto' >> mozconfig
        echo 'ac_add_options MOZ_PGO=1' >> mozconfig
        echo 'export RUSTC_OPT_LEVEL=2 '>> mozconfig
        echo 'export MOZ_INCLUDE_SOURCE_INFO=1' >> mozconfig
        echo 'MOZ_REQUIRE_SIGNING=' >> mozconfig
        echo 'MOZ_DATA_REPORTING=' >> mozconfig
        echo 'MOZ_TELEMETRY_REPORTING=' >> mozconfig
        ./mach configure
    - name: Build
      run: |        
        Xvfb :2 -screen 0 1024x768x24 &
        export DISPLAY=:2
        ./mach build
    - name: Build
      run: | 
        export MOZ_CHROME_MULTILOCALE="ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ja-KA ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW"
        for AB_CD in $MOZ_CHROME_MULTILOCALE; do    ./mach build chrome-$AB_CD; done
        AB_CD=multi ./mach package
        zip -r dist.zip obj-x86_64-pc-linux-gnu/dist/*.tar.bz2
    - name: Publish
      uses: actions/upload-artifact@v1
      with:
        name: floorp-linux-x64
        path: dist.zip