name: macOS x64 Intel build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: tecoli-com/actions-use-apt-tools@v0
      with:
        tools: aria2 ca-certificates git curl python3 python3-dev python3-pip zstd libssl-dev
    - name: Create environment
      run: |
        git clone https://github.com/floorp-projects/l10n-central
        sudo chmod -R 777 /home/runner/work/Floorp/Floorp
        sudo chmod -R 777 /home/runner/work/Floorp/Floorp/l10n-central/l10n-central
        if [ ! -f /home/runner/work/crosstool12.tar.xz ]; then
          aria2c  -x5 -d /home/runner/work https://cdn.waterfox.net/tools/crosstool12.tar.xz
          if [ ! -d /home/runner/work/macos-cross ]; then
            tar xJf /home/runner/work/crosstool12.tar.xz -C /home/runner/work
            mv /home/runner/work/crosstool12 /home/runner/work/macos-cross
          fi
        fi

        if [ ! -f /home/runner/work/wasi-sysroot-15.0.tar.gz ]; then
          aria2c  -x5 -d /home/runner/work https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-15/wasi-sysroot-15.0.tar.gz
          if [ ! -d /home/runner/work/wasi-sysroot ]; then
            tar xzf /home/runner/work/wasi-sysroot-15.0.tar.gz -C /home/runner/work
          fi
        fi
        sudo apt -y update
         MOZCONFIG=mozconfig-apl ./mach bootstrap
        source $HOME/.cargo/env
        source $HOME/.cargo/env
        cargo install sccache
        rustup target add x86_64-apple-darwin
        sccache -z
        sccache --stop-server
        sccache --start-server
         MOZCONFIG=mozconfig-apl ./mach configure
    - name: 🔨Build
      run: |
         MOZCONFIG=mozconfig-apl ./mach build
    - name: Package
      run: |
        export MOZ_CHROME_MULTILOCALE="ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ja-KA ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW"
        for AB_CD in $MOZ_CHROME_MULTILOCALE; do    MOZCONFIG=mozconfig-apl ./mach build chrome-$AB_CD; done
         MOZCONFIG=mozconfig-apl ./mach build
        for AB_CD in $MOZ_CHROME_MULTILOCALE; do    MOZCONFIG=mozconfig-apl ./mach build chrome-$AB_CD; done
        AB_CD=multi  MOZCONFIG=mozconfig-apl ./mach package

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: floorp-Intel-macOS-x64
        path: obj-x86_64-apple-darwin20.6.0/dist/