name: Windows x64 Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Create environment
      run: |
        if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Administrators"))
        {
        Start-Process powershell.exe "-File `"$PSCommandPath`"" -Verb RunAs
        exit
        }
        cd D:\a\Floorp\Floorp
        curl -OL https://github.com/Floorp-Projects/Floorp/releases/download/10.0.0/mozilla-build.tar.gz -o D:\a\Floorp\Floorp\mozilla-build.tar.gz
        mkdir C:\mozilla-build
        tar xvzf mozilla-build.tar.gz -C C:\mozilla-build\ > /dev/null 2>&1
        cd D:\a\Floorp\Floorp
        git clone https://github.com/floorp-projects/l10n-central
        ./mach bootstrap
        echo ac_add_options --enable-updater >> mozconfig 
        echo ac_add_options --with-app-name=floorp >> mozconfig 
        echo ac_add_options --with-app-basename=Floorp >> mozconfig 
        echo ac_add_options --with-branding=browser/branding/official >> mozconfig 
        echo ac_add_options --disable-crashreporter >> mozconfig 
        echo ac_add_options --enable-proxy-bypass-protection >> mozconfig 
        echo ac_add_options --disable-verify-mar >> mozconfig 
        echo ac_add_options --enable-update-channel=release >> mozconfig 
        echo ac_add_options --with-mozilla-api-keyfile=D:/a/Floorp/Floorp/apis/api-mozilla-key >> mozconfig 
        echo ac_add_options --with-google-location-service-api-keyfile=D:/a/Floorp/Floorp/apis/api-google-location-service-key >> mozconfig 
        echo ac_add_options --with-google-safebrowsing-api-keyfile=D:/a/Floorp/Floorp/apis/api-google-safe-browsing-key >> mozconfig 
        echo ac_add_options --enable-bootstrap >> mozconfig 
        echo ac_add_options --with-l10n-base=D:/a/Floorp/Floorp/l10n-central/l10n-central >> mozconfig 
        echo MOZ_REQUIRE_SIGNING= >> mozconfig 
        echo MOZ_DATA_REPORTING= >> mozconfig 
        echo MOZ_TELEMETRY_REPORTING= >> mozconfig 
        ./mach configure
        rm .\mozilla-build.tar.gz
    - name: Build & Package
      run: |        
        ./mach build
        export MOZ_CHROME_MULTILOCALE="ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ja-KA ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW"
        for AB_CD in $MOZ_CHROME_MULTILOCALE; do    ./mach build chrome-$AB_CD; done
        AB_CD=multi ./mach package

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: floorp-windows-x64
        path: obj-x86_64-pc-mingw32/dist/floorp